-- create table items (
-- item_id serial primary key,
-- name_item varchar (100) not null,
-- price smallint not null)
-- insert into items (name_item, price)
-- values ('Small_desk', 100),
-- ('Large_desk', 300),
-- ('Fan', 80)
-- select * from items
-- select * from items where price > 80
-- 
-- create table customers (
-- customer_id serial primary key,
-- first_name varchar (50) not null,
-- last_name varchar (100) not null)
-- insert into customers (first_name, last_name)
-- values ('Greg', 'Jones'),
-- ('Sandra', 'Jones'),
-- ('Scott', 'Scott'),
-- ('Trevor', 'Green'),
-- ('Melonie', 'Johnson')
-- select * from customers where last_name = 'Smith'
-- select * from customers where last_name = 'Jones'
-- select * from customers where first_name != 'Scott'
-- select * from items order by price ASC;
-- select * from items where price >= 80 order by price DESC;
-- select first_name, last_name from customers order by first_name ASC limit 3;
-- select last_name from customers order by last_name DESC;

